spring:
  application:
    name: liarsdice

  datasource:
    url: jdbc:postgresql://localhost:5432/liarsdice
    username: liarsdice_user
    password: liarsdice_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.example.liarsdice: DEBUG
    org.springframework.security: DEBUG