spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/liarsdice
    username: liarsdice_user
    password: liarsdice_password

logging:
  level:
    com.example.liarsdice: INFO
    org.springframework.security: INFO